export const DELETE_RECIPE = 'DELETE_RECIPE';
export const END_EDIT_RECIPE = 'END_EDIT_RECIPE';
export const SAVE_NEW_EDITED_RECIPE = 'SAVE_NEW_EDITED_RECIPE';
export const SAVE_NEW_RECIPE = 'SAVE_NEW_RECIPE';
export const START_EDIT_RECIPE = 'START_EDIT_RECIPE';